import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    min-width: 300px;
    min-height: 250px;
    VerticalBox {
        Text {
            text: "5 + 6";
            font-size: 10pt;
            font-weight: 800;
        }

        LineEdit {
            text: "\{root.counter}";
            read-only: true;
        }

        HorizontalLayout {
            alignment: LayoutAlignment.stretch;
            spacing: 10px;
            Button {
                text: "7";
            }

            Button {
                text: "8";
            }

            Button {
                text: "9";
            }

            Button {
                text: "x";
            }
        }

        HorizontalLayout {
            spacing: 10px;
            Button {
                text: "4";
            }

            Button {
                text: "5";
            }

            Button {
                text: "6";
            }

            Button {
                text: "-";
            }
        }

        HorizontalLayout {
            spacing: 10px;
            Button {
                text: "1";
            }

            Button {
                text: "2";
            }

            Button {
                text: "3";
            }

            Button {
                text: "+";
            }
        }

        HorizontalLayout {
            spacing: 10px;
            Button {
                text: "0";
            }

            Button {
                text: "=";
                clicked => {
                    root.request-increase-value();
                }
            }
        }
    }
}
